### ISSUE TITLE
[IDEA] general navigation

### ISSUE THREAD

**Issue by jaromeyer** [isaakhanimann/psychonautwiki-journal-android#23]
The current sidebar navigation feels very clunky on a device with gesture navigation and currently many screens completely lack a back button.

My suggestion would be to switch to a bottom navigation bar to switch between the main screens (journal, statistics, safer use, settings) which allows getting rid of the 'hamburger menu' buttons in the app bar. Other screens would still be launched on top but feature a back button in the top left corner. Also many such screens (e.g. when tapping on the 'psychedelic' chip) should probably be shown in some sort of dialog instead of navigating to a completely new screen.

**Comment by isaakhanimann** [comment]
Thanks. I added back bottom navigation.

**Comment by jaromeyer** [comment]
Thank you! The new navigation feels much better. One thing I'd recommend is adding a back arrow in the appbar on all screens other than the main ones. Not so much for use as a button but rather to make it clear to the user that they have navigated away from the main screen for the active tab and that they can use the system back gesture/button to get back to the main screen. I have started adding the buttons to some screens, is there a better way to do this globally rather than having to pass a navigateBack function and manually adding the button for every screen?

**Comment by isaakhanimann** [comment]
Glad to hear. Yes, I guess a back button makes sense. I thought that maybe in Android people are used to press the dedicated back button to go to the previous screen.
By the way you can also tap the selected tab again to have it pop to the root.
I think there's no way to add the back button globally because it needs indirect access to the navigationController. It would be very nice if you could make a PR with all the back buttons.
