### ISSUE TITLE
Feature Request: Have the graph show different substances relative to their dose intensity

### ISSUE THREAD

**Issue by smiba** [isaakhanimann/psychonautwiki-journal-android#49]
Right now when combining substances, the graph doesn't take their dose intensity into consideration.

if you take 50g of alcohol, and 1mg of caffeine, this peaks at the exact same height in the graph even though the caffeine is  negligible.

![Screenshot_20240510_120602_Journal](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/3308142/5ad59d3d-2dd2-45db-866e-dd31f742e007)

It would make more sense for the y-axis of the graph to be made in reference to the strength of the dose at that point. We already know what dosages are light/moderate/heavy etc, why not graph according to this?

**Comment by isaakhanimann** [comment]
Because its difficult to compare strength of different substances. Compare a common dose of Caffeine with a common dose of LSD. So better to not compare them at all. Also you can't really make an absolute y scale because some people e.g. take 5x the heavy dose. Also I don't want this gameification where people try to reach the top of the timeline. So I think the sensible thing is to just have the right relative to other ingestions of the same substance in the same experience.

**Comment by isaakhanimann** [comment]
I think I get what you mean now. Doses are always converted to a kind of strength scale and then the heights can be compared across substances. But the strongest dose still takes the full height no matter how light it is.

I think its a good idea. Just have to handle unknown doses or unknown strength of dose gracefully.

Please create a PR with the changes

**Comment by isaakhanimann** [comment]
I implemented this for the iOS app. Its the next thing that I will also implement for the Android app.

**Comment by isaakhanimann** [comment]
I just implemented it for Android too

**Comment by smiba** [comment]
Thank you! Much appreciated <3
